Portfolio: Contact form
Devtiwo/Portfolio pull request #4
Opened 2021-11-30 16:24 UTC by Devtiwo

In this project, I :

- Made changes to the about me section.
- Worked with my coding partner in adding contact me form
- Added more images to the images folder
- Added styles for the contact me section

2021-11-30 17:14 UTC, Rustamxon7 requested changes
> ## STATUS: CHANGES REQUIRED 🟡
> Hi @joskalenda,
> 
> Great work on making the changes requested by the previous reviewer, but there are still some which aren't addressed yet.
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ![really close](https://camo.githubusercontent.com/610ba39845cbc5bfce08f092117aa5573447b79bd89160db59ada95582b1836c/68747470733a2f2f632e74656e6f722e636f6d2f66754b6a7462743762344541414141642f7265616c6c792d7265616c6c792d636c6f73652d62696c6c2d6d75727261792e676966)
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 17:14 UTC, Rustamxon7 commented on index.html
> +             <textarea name="message" maxlength="500" required>Enter text here</textarea>
- [ ] You have used placeholder in other elements inside form, why don't you use also for `<textarea>`? Please kindly remove text and closing tag and enter your `Enter text here` inside placeholder like this `<textarea name="message" maxlength="500" placeholder="Enter text here" required>`. If you put your text inside placeholder your client will be able to fill the form without removing old text again 😊🙌

You can see the difference between what happens if I want to type something inside textarea

| Yours | Original |
  | ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/69011963/144094489-7c0b1fa0-ab44-4b8f-b477-b0165ca69631.png) |![image](https://user-images.githubusercontent.com/69011963/144094781-2d249206-b7fe-4df4-a721-a068486b0f6c.png)|

2021-11-30 17:34 UTC, ShoiraTa approved these changes
## Status: Approved :heavy_check_mark:

Hi @Devtiwo  and @mugishasam123 ,  

You have done a great job working on required changes! Now `<textarea>` has a placeholder!
Your project is complete! Congratulations!  🎉💯🌟 

## Good Points 👍 
- Awesome UI ✔️ 
- Followed Figma template ✔️ 
- All input fields have the correct `type` attribute ✔️
- Form uses proper `action` and `method` attributes ✔️
- All input fields have correct associated placeholder text. ✔️

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 17:52 UTC, merged

2021-12-02 07:26 UTC, banlon-jones reviewed
# Excellent work @Devtiwo 

Your code is excellent and you have clearly demonstrated your understanding of the project.
However there are some changes to make, please check my comments below and make all required changes. submit for re-review when done
It was a pleasure reviewing your work, and we look forward to seeing future submissions from you.

## Project highlights:
- All linter checks are passing :heavy_check_mark:
- Your PR has a descriptive title/summary of the implemented changes :memo:
-  Descriptive commits and correct use of the GitHub Flow :fire:

[optional] Great job, adding the alt attribute in the image tag however alt` attribute should be descriptive this is because the text is displayed when the image can't load because of slow connection, and the screen reader can read the text to visually impaired users to better understand an on-page image 

## :+1: :+1: 
[OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

2021-12-02 07:26 UTC, banlon-jones commented on index.html
>               <button type="submit">Get in touch</button>
Great job, @Devtiwo making the **Textarea** tag required this way users must type their message
## impressive

2021-12-02 07:26 UTC, banlon-jones commented on index.html
> -             <textarea maxlength="500" required>Enter text here</textarea>
great job, including field constraints like **maxlength** and **required**