Portfolio: Desktop version
Devtiwo/Portfolio pull request #6
Opened 2021-12-02 19:46 UTC by Devtiwo

In this project, I :

- Added a few elements to the index file for the desktop version.
- Added Media queries to the style file to cater for the desktop version.
- Added more images to the images folder.

2021-12-02 21:41 UTC, andersonlebon requested changes
## Hi @Devtiwo 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 21:41 UTC, andersonlebon commented on style.css
> +    width: 1440px;
- [ ] As one of the requirements says that you should stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). To adapt your design to different large screens I suggest that you use the `width: 100%` instead of width with a fixed value(`width: 1440px`). this will eliminate the blanc space at the right of your design
### Your design 
![Screenshot from 2021-12-02 23-22-28](https://user-images.githubusercontent.com/65068771/144505163-dfc71b77-0866-4c2f-aa59-7fdaa737017b.png)
### The template
![Screenshot from 2021-12-02 23-23-51](https://user-images.githubusercontent.com/65068771/144505534-0e4667e1-1fb8-4a63-bb52-24ba463eddd2.png)

2021-12-02 21:41 UTC, andersonlebon commented on style.css
> +    width: 1440px;
- [ ] As one of the requirements says that you should stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). To adapt your design to different large screens I suggest that you use the `width: 100%` instead of width with a fixed value(`width: 1440px`). this will eliminate the blanc space at the right of your design
### Your design 
![Screenshot from 2021-12-02 23-22-28](https://user-images.githubusercontent.com/65068771/144505163-dfc71b77-0866-4c2f-aa59-7fdaa737017b.png)
### The template
![Screenshot from 2021-12-02 23-23-51](https://user-images.githubusercontent.com/65068771/144505534-0e4667e1-1fb8-4a63-bb52-24ba463eddd2.png)

2021-12-02 21:41 UTC, andersonlebon commented on style.css
> +    width: 1440px;
- [ ] As one of the requirements says that you should stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). To adapt your design to different large screens I suggest that you use the `width: 100%` instead of width with a fixed value(`width: 1440px`). this will eliminate the blanc space at the right of your design
### Your design 
![Screenshot from 2021-12-02 23-22-28](https://user-images.githubusercontent.com/65068771/144505163-dfc71b77-0866-4c2f-aa59-7fdaa737017b.png)
### The template
![Screenshot from 2021-12-02 23-23-51](https://user-images.githubusercontent.com/65068771/144505534-0e4667e1-1fb8-4a63-bb52-24ba463eddd2.png)

2021-12-02 21:41 UTC, andersonlebon commented on style.css
> +    flex-direction: column;
- [ ] As one of the requirements says that you should stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). To adapt your design to different large screens I suggest that you use the `width: 100%` instead of width with a fixed value(`width: 1440px`). this will eliminate the blanc space at the right of your design
### Your design 
![Screenshot from 2021-12-02 23-22-28](https://user-images.githubusercontent.com/65068771/144505163-dfc71b77-0866-4c2f-aa59-7fdaa737017b.png)
### The template
![Screenshot from 2021-12-02 23-23-51](https://user-images.githubusercontent.com/65068771/144505534-0e4667e1-1fb8-4a63-bb52-24ba463eddd2.png)

- [ ] Kindly remove  also the `  padding: 0 118px;` or just reduce it.

2021-12-02 21:41 UTC, andersonlebon commented on style.css
> +  }
- [ ] As one of the requirements says that you should stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). To adapt your design to different large screens I suggest that you use the `width: 100%` instead of width with a fixed value. this will eliminate the blanc space at the right of your design
### Your design 
![Screenshot from 2021-12-02 23-22-28](https://user-images.githubusercontent.com/65068771/144505163-dfc71b77-0866-4c2f-aa59-7fdaa737017b.png)
### The template
![Screenshot from 2021-12-02 23-23-51](https://user-images.githubusercontent.com/65068771/144505534-0e4667e1-1fb8-4a63-bb52-24ba463eddd2.png)

2021-12-02 21:41 UTC, andersonlebon commented on style.css
> -  height: 590px;
- [ ] I would suggest also removing the overflow-x in your design, you can do it by adding this to your CSS
````
HTML {
   overflow-x: hidden;
}
````

## In Brief, remove the black space at the right of your design.

2021-12-02 23:00 UTC, rotimiazeez requested changes
# Hi @Devtiwo 👋, 

### Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.👇

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 01:02 UTC, leolpaz approved these changes
Hi @Devtiwo , 

Your project is complete!
Congratulations! 🎉🎉 

To highlight:

- Congratulations on implementing the changes requested by the previous reviewer

Now there is nothing left to do but to merge it! 🏆 

![](https://media2.giphy.com/media/l3fQc3aCV0HqpzWcU/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 05:24 UTC, merged